-- Database

-- CREATE DATABASE SALUD_DATA_CENTER;
-- USE SALUD_DATA_CENTER;

-- Tabla categoria

CREATE TABLE IF NOT EXISTS categoria
(
    id integer NOT NULL AUTO_INCREMENT,
    Tipo VARCHAR(255) COLLATE latin1_general_ci,
    Nombre character varying(255) COLLATE latin1_general_ci,
    createdAt timestamp with time zone NOT NULL,
    updatedAt timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
);

-- Tabla doctores

CREATE TABLE IF NOT EXISTS doctores
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula character varying(255) COLLATE Latin1_General_CI_AS,
    nombreusuario character varying(255) COLLATE Latin1_General_CI_AS,
    nombre character varying(255) COLLATE Latin1_General_CI_AS,
    contrasena character varying(255) COLLATE Latin1_General_CI_AS,
    email character varying(255) COLLATE Latin1_General_CI_AS,
    dni integer,
);

-- Tabla empresas

CREATE TABLE IF NOT EXISTS empresas
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) COLLATE Latin1_General_CI_AS,
    nombreusuario character varying(255) COLLATE Latin1_General_CI_AS,
    contrasena character varying(255) COLLATE Latin1_General_CI_AS,
    contact character varying(255) COLLATE Latin1_General_CI_AS,
    logo character varying(255) COLLATE Latin1_General_CI_AS,
    url character varying(255) COLLATE Latin1_General_CI_AS,
);

-- Tabla pacientes

CREATE TABLE IF NOT EXISTS pacientes
(
    id integer primary key generated by default as identity,
    Nombre character varying(255) COLLATE Latin1_General_CI_AS,
    Apellido character varying(255) COLLATE Latin1_General_CI_AS,
    Dni integer,
    Email character varying(255) COLLATE Latin1_General_CI_AS,
    Telefono integer,
    Telefono2 integer,
    Sintomas character varying(255) COLLATE Latin1_General_CI_AS,
    Tratamiento character varying(255) COLLATE Latin1_General_CI_AS,
    Diagnostico character varying(255) COLLATE Latin1_General_CI_AS,
    Exp_Medico character varying(255) COLLATE Latin1_General_CI_AS,
    createdAt timestamp with time zone NOT NULL,
    updatedAt timestamp with time zone NOT NULL,
);

-- Tabla productos

CREATE TABLE IF NOT EXISTS productos
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdAt timestamp with time zone NOT NULL,
    updatedAt timestamp with time zone NOT NULL,
    TipoId integer,
    CategoriaId integer,
    CONSTRAINT "productos_CategoriaId_fkey" FOREIGN KEY ("CategoriaId")
        REFERENCES public.categoria (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT "productos_TipoId_fkey" FOREIGN KEY ("TipoId")
        REFERENCES public.tipos (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- Tabla registros

CREATE TABLE IF NOT EXISTS registros
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombrepaciente character varying(255) COLLATE Latin1_General_CI_AS,
    doctorasignado character varying(255) COLLATE Latin1_General_CI_AS,
    fechaemision character varying(255) COLLATE Latin1_General_CI_AS,
    razondevisita character varying(255) COLLATE Latin1_General_CI_AS,
    tratamiento character varying(255) COLLATE Latin1_General_CI_AS,
    indicaciones character varying(255) COLLATE Latin1_General_CI_AS,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
);

-- Tabla subCategorias

CREATE TABLE IF NOT EXISTS sub_categoria
(
    id integer primary key generated by default as identity,
    "Tipo" character varying(255) COLLATE Latin1_General_CI_AS,
    "Nombre" character varying(255) COLLATE Latin1_General_CI_AS,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "CategoriaId" integer,
    CONSTRAINT "Catego" FOREIGN KEY ("CategoriaId")
        REFERENCES public.categoria (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL,
);

-- Tabla tipo

CREATE TABLE IF NOT EXISTS tipo
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca character varying(255) COLLATE Latin1_General_CI_AS,
    modelo character varying(255) COLLATE Latin1_General_CI_AS,
    anio character varying(255) COLLATE Latin1_General_CI_AS,
    precio character varying(255) COLLATE Latin1_General_CI_AS,
    descripcion text COLLATE Latin1_General_CI_AS,
    ficha_tecnica character varying(255) COLLATE Latin1_General_CI_AS,
    imagenes character varying(255) COLLATE Latin1_General_CI_AS,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
);