// const.js
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//const_stats.js
export const GET_STONKS_SUCCESS = 'GET_STONKS_SUCCESS';
export const GET_STONKS_FAILURE = 'GET_STONKS_FAILURE';

// PATIENTS
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAILURE = 'GET_PATIENTS_FAILURE';
export const POST_PATIENTS_SUCCESS = 'POST_PATIENTS_SUCCESS';
export const POST_PATIENTS_FAILURE = 'POST_PATIENTS_FAILURE';
export const PUT_PATIENTS_SUCCESS = 'PUT_PATIENTS_SUCCESS';
export const PUT_PATIENTS_FAILURE = 'PUT_PATIENTS_FAILURE';

// RECORDS
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORDS_FAILURE = 'GET_RECORDS_FAILURE';
export const POST_RECORDS_SUCCESS = 'POST_RECORDS_SUCCESS';
export const POST_RECORDS_FAILURE = 'POST_RECORDS_FAILURE';

// PRODUCTS
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const POST_PRODUCTS_SUCCESS = 'POST_PRODUCTS_SUCCESS';
export const POST_PRODUCTS_FAILURE = 'POST_PRODUCTS_FAILURE';
